config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root "home#index"
  mount Sidekiq::Web => "/sidekiq"

  # get 'home/index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  resources :users do
    resources :addresses
    resources :memberships
    resources :payments
    resources :enrollments
  end
  resources :trainer_coaches do
    resources :courses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments, dependent: :destroy 
  has_many :users, through: :enrollments, source: :user, dependent: :destroy 

  belongs_to :trainer_coach

  validates :class_name, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :capacity, presence: true


  # accepts_nested_attributes_for :enrollments

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
  validates :enrollment_date, presence:  true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy 
  has_many :users, through: :payments, dependent: :destroy 


  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  # validate :check_start_end_date_for_status

  # def check_start_end_date_for_status
  #   if start_date  <= Date.today
  #     errors.add(:start_date, "aren't less than from today.")      
  #   end
  # end
  

  
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :membership

  validates :payment_date, presence: true
  validates :amount, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/trainer_coach.rb
class TrainerCoach < ApplicationRecord
  resourcify

  has_many :courses, dependent: :destroy 

  validates :first_name, presence: true 
  validates :last_name, presence: true 
  validates :phone_number, presence: true 
  validates :expertise, presence: true 



end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_one :address, dependent: :destroy 
  accepts_nested_attributes_for :address

  # has_one :payment
  has_many :memberships, dependent: :destroy 
  has_many :payments, through: :memberships, dependent: :destroy 

  has_many :enrollments, dependent: :destroy 
  has_many :courses, through: :enrollments, source: :course, dependent: :destroy 

  validates :first_name, presence: true 
  validates :last_name, presence: true 
  validates :date_of_birth, presence: true 
  validates :email, presence: true 
  validates :phone_number, presence: true 
  validates :gender, presence: true 







  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    # byebug
    @trainer_coach = TrainerCoach.find(params[:trainer_coach_id])
    @courses = @trainer_coach.courses.all
    # @courses = Courses.all

  end
  
  # def show
  #   # @trainer_coach = TrainerCoach.find(params[:course_id])
  #   @course = Course.find(params[:id ])
  # end

  def new
    @trainer_coach = TrainerCoach.find(params[:trainer_coach_id])
    @course = @trainer_coach.courses.new
  end

  def create
    
    @trainer_coach= TrainerCoach.find(params[:trainer_coach_id])
    @course = @trainer_coach.courses.new(course_params)
    if @course.save
      redirect_to @trainer_coach
    else 
      render :new, status: :unprocessable_entity
     end
  end

  # def edit
  #   # @course = Course.find(params[:id]
  #   byebug
  #   @trainer_coach = TrainerCoach.find(params[:trainer_coach_id])
  #   @course = @trainer_coach.course.find(params[:id])
  # end

  # def update
  #   @course = Course.find(params[:id])

  #   if @course.update(course_params)
  #     redirect_to @course
  #   else 
  #     render :new, status: :unprocessable_entity
  #   end

  # end

  # def destroy
  #   @course =Course.find(params[:id])
  #   @course.destroy

  #   redirect_to root_path, status: :see_other

  # end


  private
  def course_params
    params.require(:course).permit( :description, :start_time, :end_time, :capacity,:class_name, :trainer_coach_id )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to users_path
    end
  end
end

app/controllers/trainer_coaches_controller.rb
class TrainerCoachesController < ApplicationController
  # before_action :authenticate_user!
  def index
    @trainer_coaches = TrainerCoach.all
  end
  
  def show
    @trainer_coach = TrainerCoach.find(params[:id ])
  end

  def new
    @trainer_coach = TrainerCoach.new
  end

  def create

    @trainer_coach = TrainerCoach.new(trainer_coach_params)

    if @trainer_coach.save
      redirect_to  trainer_coaches_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @trainer_coach = TrainerCoach.find(params[:id])

    if @trainer_coach.update(trainer_coach_params)
      redirect_to @trainer_coach
    else 
      render :new, status: :unprocessable_entity
    end

  end
  def edit
    @trainer_coach = TrainerCoach.find(params[:id])

  end


  # def destroy
  #   @trainer_coach =TrainerCoach.find(params[:id])
  #   @trainer_coach.destroy

  #   redirect_to root_path, status: :see_other

  # end

  private

  def trainer_coach_params
    params.require(:trainer_coach).permit(:first_name, :last_name, :phone_number,:expertise )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  # def index
  #   @users = User.all
  # end
  
  def show
    @user = User.find(params[:id ])
  end

  # def new
  #   @user = User.new
  # end

  # def create

  #   @user = User.new(user_params)

  #   if @user.save

  #     redirect_to @user
  #   else 
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  # def update
  #   @user = User.find(params[:id])

  #   if @user.update(user_params)
  #     redirect_to @user
  #   else 
  #     render :new, status: :unprocessable_entity
  #   end

  # end
  # def edit
  #   @user = User.find(params[:id])

  # end


  # def destroy
  #   @user =User.find(params[:id])
  #   @user.destroy

  #   redirect_to root_path, status: :see_other

  # end

  private

  # def user_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :password, :date_of_birth, :phone_number, :gender, address: [:house_no,:street,:city,:state,:postal_code])
  # end

  

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/trainer_coaches_helper.rb
module TrainerCoachesHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trainer_coaches/_form.html.erb
<!--

<!DOCTYPE html>
<html>
<head>
  <title>Edit Details</title>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css' %>
   Add any other custom stylesheets if needed 
</head>
<body>
  <div class="container mt-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Edit Details</h1>

        <%= form_with model: @trainer_coach do |form| %>
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "form-control" %>

          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "form-control" %>

          <%= form.label :phone_number %>
          <%= form.text_field :phone_number, class: "form-control" %>

          <%= form.label :expertise %>
          <%= form.select :expertise, ["yoga", "Weight_lifting", "Aerobics"], {}, class: "form-control" %>

          <%= form.submit class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</body>
</html>

-->





<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Ion Icons Js -->
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <!-- JS -->
    <!-- CSS -->
    <%#= stylesheet_link_tag "trainer/index" %>
    <%= stylesheet_link_tag "trainer/form" %>
    
    <%= stylesheet_link_tag 'home/style' %>
</head>
<body>
    <!-- Menu -->
    <div class="menu">
        <div class="container flex">
            <!-- Mobile Button -->
            <div class="mobile-btn">
                <ion-icon name="grid"></ion-icon>
            </div>
            <div class="logo">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/logo.png', alt: '') %>
            </div>
            <ul class="nav">
                <li class="nav-item"><%= link_to 'Home', '/' %></li>
                <li class="nav-item"><%= link_to 'Trainer Details', '/trainer_coaches' %></li>
            </ul>
            <%#= link_to 'Login', '/users/sign_in', class: 'btn' %>
            <%= link_to "Sign Out", destroy_user_session_path, class: 'btn', data: { "turbo-method": :delete } %>
        </div>
    </div>
    <!-- End Menu -->
    <!-- Login Page -->
    <div class="container">
    <div class="flex">

        <div class="container mt-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Trainer Forms</h1>


        <%= form_with model: @trainer_coach do |form| %>
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "form-control" %>

          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "form-control" %>

          <%= form.label :phone_number %>
          <%= form.text_field :phone_number, class: "form-control" %>

          <%= form.label :expertise %>
          <%= form.select :expertise, ["yoga", "Weight_lifting", "Aerobics"], {}, class: "form-control" %>

          <%= form.submit class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>





          

                 
      </div>
    </div>
  </div>


    <!-- Login endPage -->

  




<!-- Footer -->
<footer class="footer">
    <div class="container flex">
        <p class="tertiary">
            &copy; <%= Time.now.year %> Programmer Cloud. All Rights Reserved.
        </p>
    </div>
</footer>
<!-- End Footer -->
<script src="script.js"></script>
</body>
</html>
  

app/views/trainer_coaches/edit.html.erb
<!--
<h1> Edit Details </h1>


<%= form_with model: @trainer_coach do |form| %>

  <%= form.label :first_name %>
  <%= form.text_field :first_name %><br>

  <%= form.label :last_name %>
  <%= form.text_field :last_name %><br>

  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %><br>

  <%= form.label :expertise %>
  <%= form.select :expertise, ["yoga", "Weight_lifting", "Aerobics"] %><br>

  <%= form.submit  %>
<% end %>
-->

<%= render "form"%>

app/views/trainer_coaches/index.html.erb
<!--
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Your Logo</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Member</a>
          </li>
       

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>

        </ul>
        <form class="">

         <a class="btn btn-outline-primary mr-2" href="/users">Account</a>
          <a class="btn btn-outline-success" href="#">Become member</a>
        <p class="btn btn-outline-primary mr-2" >
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
        </p>
        </form>

      </div>
    </div>
  </nav>
</div>

-->







<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PGC-GYM Landing Page</title>
    <!-- Ion Icons Js -->
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <!-- JS -->
    <!-- CSS -->
    <%= stylesheet_link_tag "trainer/index" %>
    <%= stylesheet_link_tag 'home/style' %>
</head>
<body>
    <!-- Menu -->
    <div class="menu">
        <div class="container flex">
            <!-- Mobile Button -->
            <div class="mobile-btn">
                <ion-icon name="grid"></ion-icon>
            </div>
            <div class="logo">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/logo.png', alt: '') %>
            </div>
            <ul class="nav">
                <li class="nav-item"><%= link_to 'Home', '/' %></li>
                <li class="nav-item"><%= link_to 'Features', '#why-us' %></li>
                <li class="nav-item"><%= link_to 'Explore', '#explore' %></li>
                <li class="nav-item"> <%= link_to 'Account', user_path(current_user.id) %> </li>
            </ul>
            <%#= link_to 'Login', '/users/sign_in', class: 'btn' %>
            <%= link_to "Sign Out", destroy_user_session_path, class: 'btn', data: { "turbo-method": :delete } %>
        </div>
    </div>
    <!-- End Menu -->
    <!-- Login Page -->
    <div class="container">
    <div class="flex">
      <div class="header">
        <div class="text">
        </div>
        <div class="visual">
          <%#= image_tag 'path-to-your-image.jpg', alt: 'Login Visual' %>
        </div>
      </div>
    </div>
    <div class="section"style="background: radial-gradient(#111, #071a1a);">
      <div class="flex">
        <div class="card" style="width: 95.5rem; margin-top: 7px;
  margin-bottom: 3px;
  margin-right: 31px;
  margin-left: -5px;
">
  <div class="card-body">
    <h3>All Trainer Details</h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Trainer Name</th>
          <th>Expertise</th>
          <th>Show Trainer Details</th>
        </tr>
      </thead>
      <tbody>
        <% @trainer_coaches.each do |trainer| %>
        <tr>
          <td><%= trainer.first_name %></td>
          <td><%= trainer.expertise %></td>
          <td><a href="/trainer_coaches/<%= trainer.id %>" class="btn btn-primary btn-sm">Show Trainer Details</a></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
</div>




   
   
                 
      </div>
    </div>
  </div>


    <!-- Login endPage -->

  

    <!-- Why Us -->
    <div class="section" id="why-us">
        <div class="container flex">
            <div class="text">
                <h2 class="primary mb">Why Choose Us?</h2>
                <h3 class="secondary mb">Consulatation with Expert.</h3>
                <p class="tertiary">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias quos
                    maxime tempore?
                </p>
                <h3 class="secondary mb">Consulatation with Expert.</h3>
                <p class="tertiary">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias quos
                    maxime tempore?
                </p>
            </div>
            <div class="visual">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/why-us.png', alt: '') %>
            </div>
        </div>
    </div>
    <!-- End Why Us -->

    <!-- Explore -->
    <div class="section" id="explore">
        <div class="container flex">
            <div class="visual">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/explore.jpg', alt: '') %>
            </div>
            <div class="text">
                <h2 class="primary mb">
                    Explore Our Fitness <br />
                    Studio
                </h2>
                <p class="tertiary mb">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
                    esse vitae ratione quos maiores eveniet temporibus illum! Eligendi
                    amet officia unde sint totam ut optio. Molestiae, illo quia?
                </p>
                <%= link_to 'Get Started Now', '/users/sign_up', class: 'btn mt' %>
            </div>
        </div>
    </div>
    <!-- End Explore -->


<!-- Footer -->
<footer class="footer">
    <div class="container flex">
        <p class="tertiary">
            &copy; <%= Time.now.year %> Programmer Cloud. All Rights Reserved.
        </p>
    </div>
</footer>
<!-- End Footer -->
<script src="script.js"></script>
</body>
</html>
  

app/views/trainer_coaches/new.html.erb
<%=  render "trainer_coaches/form" %>

app/views/trainer_coaches/show.html.erb
<!--
<div class="container-flouid" >
  <nav class="navbar navbar-expand-lg bg-light" >
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Modern Gym</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/trainer_coaches">Trainers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" <%=link_to "Trainer Courses", trainer_coach_courses_path(@trainer_coach) %> </a>
          </li>
              <li class="nav-item">
            <a class="nav-link active" href="/users/sign_out" >Sign out </a>
          </li>
          
 

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>
 
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>

        </ul>


      </div>
    </div>
  </nav>
</div>

      
<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/<%=@trainer_coach.id%>/courses/new" class="btn btn-primary">Add Courses</a>
<%end%>  

<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/new" class="btn btn-primary"  >Add trainer</a>  
<%end%>

<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/<%=@trainer_coach.id%>/edit" class="btn btn-primary">Update</a>
<%end%>
  -->




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PGC-GYM Landing Page</title>
    <!-- Ion Icons Js -->
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <!-- JS -->
    <!-- CSS -->
    <%= stylesheet_link_tag 'home/style' %>
    <%= stylesheet_link_tag 'trainer/show' %>

</head>
<body>
    <!-- Menu -->
    <div class="menu">
        <div class="container flex">
            <!-- Mobile Button -->
            <div class="mobile-btn">
                <ion-icon name="grid"></ion-icon>
            </div>
            <div class="logo">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/logo.png', alt: '') %>
            </div>
            <ul class="nav">
                <li class="nav-item"><%= link_to 'Home', '/' %></li>
                <li class="nav-item"><%= link_to 'Trainer Courses', '#why-us' %></li>
                <li class="nav-item"><%= link_to 'Explore', '#explore' %></li>
                <li class="nav-item"><%= link_to 'Account', user_path(current_user.id) %></li>
                <li class="nav-item"><%=link_to "All Courses", trainer_coach_courses_path(@trainer_coach) %></li>
            </ul>
            <%#= link_to 'Login', '/users/sign_in', class: 'btn' %>
            <%= link_to "Sign Out", destroy_user_session_path, class: 'btn', data: { "turbo-method": :delete } %>
        </div>
    </div>
    <!-- End Menu -->
    <!-- Login Page -->
    <div class="container">
    <div class="flex">

      <div class="header">
        <div class="text">
        </div>
        <div class="visual">
          <%#= image_tag 'path-to-your-image.jpg', alt: 'Login Visual' %>
        </div>
      </div>
    </div>
    <div class="section"style="background: radial-gradient(#111, #071a1a);">
      <div class="flex">

        <table>
          <tr>
            <td>
              <div class="card" style=" margin-left: 19px;">
                <div class="card-body">
                  <h3>Trainer Detail</h3>

                  <h5 class="card-title">Name:</h5>
                  <p class="card-text"><%= @trainer_coach.first_name %> <%= @trainer_coach.last_name %></p>
                  <h5 class="card-title">Mobile N0.:</h5>
                  <p class="card-text"><%= @trainer_coach.phone_number %></p>
                  <h5 class="card-title">Expertise:</h5>
                  <p class="card-text"><%= @trainer_coach.expertise %></p>
                </div>
              </div>
            </td>
        
          </tr>
        </table>
       



   
   
                 
      </div>
    </div>
  </div>


    <!-- Login endPage -->

  

    <!-- Why Us -->
    <div class="section" id="why-us" style="background: radial-gradient(#111, #071a1a);">
        <div class="container flex">
            <div class="text">
              <!-- Trainer courses details start  -->
              <table>


  <tr>
    <td>
      <div class="card" style="width: 60rem; margin-left: 19px;">
        <div class="card-body">
          <h3>Courses Details</h3>

                

            <table class="card-table">
                <thead>
                    <tr>
                        <th>Course ID</th>
                        <th>Class Name</th>
                        <th>Class Description</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Capacity</th>
                        <th>Show Courses</th>
                    </tr>
                </thead>
                <tbody>
                    <% @trainer_coach.courses.each do |course| %>
                        <tr>
                            <td><%= course.id %></td>
                            <td><%= course.class_name %></td>
                            <td><%= course.description %></td>
                            <td><%= course.start_time.in_time_zone('Asia/Kolkata').strftime("%H:%M %Z") %></td>
                            <td><%= course.end_time.in_time_zone('Asia/Kolkata').strftime("%H:%M %Z") %></td>
                            <td><%= course.capacity %></td>
                            <td><a href="/trainer_coaches/<%=@trainer_coach.id%>/courses/<%course.id%>" class="btn btn-primary">Show all Courses</a>
              </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>

        </div>
      </div>
    </td>
  </tr>
</table>

<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/<%=@trainer_coach.id%>/courses/new" class="btn btn-primary">Add Courses</a>
<%end%>  

<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/new" class="btn btn-primary"  >Add trainer</a>  
<%end%>

<% if current_user.has_role? :admin %>
<a href="/trainer_coaches/<%=@trainer_coach.id%>/edit" class="btn btn-primary">Update</a>
<%end%>


              <!-- Trainer Courses Details end-->

               <!-- <h2 class="primary mb">Why Choose Us?</h2>
                <h3 class="secondary mb">Consulatation with Expert.</h3>
                <p class="tertiary">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias quos
                    maxime tempore?
                </p>
                <h3 class="secondary mb">Consulatation with Expert.</h3>
                <p class="tertiary">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias quos
                    maxime tempore?
                </p>
            </div>
            <div class="visual">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/why-us.png', alt: '') %>
            </div>
            -->
        </div>
    </div>
    <!-- End Why Us -->

    <!-- Explore -->
    <div class="section" id="explore">
        <div class="container flex">
            <div class="visual">
                <%= image_tag('https://raw.githubusercontent.com/programmercloud/pgc-gym/main/img/explore.jpg', alt: '') %>
            </div>
            <div class="text">
                <h2 class="primary mb">
                    Explore Our Fitness <br />
                    Studio
                </h2>
                <p class="tertiary mb">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis
                    esse vitae ratione quos maiores eveniet temporibus illum! Eligendi
                    amet officia unde sint totam ut optio. Molestiae, illo quia?
                </p>
                <%= link_to 'Get Started Now', '/users/sign_up', class: 'btn mt' %>
            </div>
        </div>
    </div>
    <!-- End Explore -->


<!-- Footer -->
<footer class="footer">
    <div class="container flex">
        <p class="tertiary">
            &copy; <%= Time.now.year %> Programmer Cloud. All Rights Reserved.
        </p>
    </div>
</footer>
<!-- End Footer -->
<script src="script.js"></script>
</body>
</html>
  